### PR TITLE
Next fix tests

### LINKED ISSUE #75: TemplateVerified handler doesn't change 'verified' status
Currently TemplateVerified handler casts events templateId toHexString rather than regular string, therefore no saleTemplates are matched.

EDIT: Same applies to TemplateRemoved handler.

### PR DESCRIPTION
**Pull request by denciu**
Changes:
 - testing setup refactor - previously, setup teardown happened after each test by recreating docker-compose. Now, Docker compose is started just once (with anonymous volumes cleanup) which speeds up testing,
 - improved ts - typings are now generated from artifacts rather than ABIs which adds more functionality to generated factories which results in better type inference and cleaner code,
 - fix existing tests and added a few more related to the participant list
 - Use `prepare-xdai` for CI build
- Closes #75

### CODE REVIEW

File: src/mappings/templateLauncher.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export function handleTemplateAdded(event: TemplateAdded): void {
  * @param event the `TemplateAdded` event
  */
 export function handleTemplateVerified(event: TemplateVerified): void {
-  let saleTemplate = Schemas.SaleTemplate.load(event.params.templateId.toHexString())
+  let saleTemplate = Schemas.SaleTemplate.load(event.params.templateId.toString())
```
Comment (adamazad) [inline src/mappings/templateLauncher.ts:42]: I think these were causing the test to fail in the first place! Thank you a lot!

**Review by adamazad — APPROVED** [review]
Thank you for your awesome work! I rebased and fixed amended this PR, but credits goes to you! :)
